apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  labels:
    component: mutating-controller
webhooks:
  - name: quay.away.cluster
    failurePolicy: Fail
    clientConfig:
      service:
        name: quay-away
        namespace: quay-away
        path: /mutate
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVQVpJT3gvRldHUjY3TkpYS01ZNHVRMUU0dHVRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01ZV1J0YVhOemFXOXVYMk5oTUNBWERUSXdNRFF5T0RFNU1UVXhNRm9ZRHpJeQpPVFF3TWpFeE1Ua3hOVEV3V2pBWE1SVXdFd1lEVlFRRERBeGhaRzFwYzNOcGIyNWZZMkV3Z2dFaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURRaHFGeGcwQ0x3UXJmZE16eXdBSHBLdmw1dmNyRFk4aHAKaUUzaTFIYzk2ZjRUeFdXQ0ZqWGZNakRtNThiUHNHdWJtMTN6OUh6aXN2Ym10NklQM2swYzgyUWh3N0Vla1lEYQp0dnUxQXkycExkemlCL3oxZ09JNmNSSGtQWWFoYmpGVjVlS1REVDFTS1M3emJlYmF4dFlKSFJQY2RpSi9ERkphCjRsemFwVnRhQmFZQysxUituR0tWN1VBd1NFVzBvaHZTaEUxUWNNdjR4bHZoVGc2ejluaDdab3Y5Kzl0bHp0ZnoKUHZCVllHbkFMNVdwV1BZeS91aG43VEFsZkJ6Q0hTVlE4a1NqUEhnU2hvNTZHbWJjYmh2NDcrOVRtdHFnTW5jZwpVbGlXTTVseEtJbGVHZVJnN1pQVUFyOVppSGZuemRRVHZkcm91VTlucmtxOW5QenVkWXROQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JCUVdpUGVjaXg0T0RtMjlkVjA4MTViSG1NQkI1ekFmQmdOVkhTTUVHREFXZ0JRV2lQZWMKaXg0T0RtMjlkVjA4MTViSG1NQkI1ekFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFBcUVYKzB6bWdJMjM4Z1QvRXpvRDJONkhwZ2hvR2hPcGJlQmZqVGViaFhpQzZqdjJ5MnlDMFJvSjRFCm5xdFdFbDVVdUJSWGdRR3VrM3ErSHB4NHR3aVlkRXNPT3VleUhlNVY4RWZIMTR4bzBZY2ZIZGlzbUZkcExvTGcKeEJGK3pDWGt2Rms0amZpZFBuSHBwWE42QzlwL3FaUm1QVG8rZVRRZE4xTFkxNEJnclFPemRsRm5sUDRkVU1uQQpGQUF0U2hHdEVlMXlDVjJsWDZOOC91U0laUzJqMTh1TXBGTmNMMUJ0a09MWDNpWHNBY3ZMTEdieGdPajNuV1ZuClg2bUZoWTVwckJoZnN6L2pjSTY1a1hISjdGWTZxbDdtbHJNRHo1NHdVMVphQVA2T0daNXdDSHA3WmEzRHoramwKeEsySWlMbVJWQVZwRzQzUjhwbDhORFVkclZabQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
    rules:
      - apiGroups: [""]
        resources:
          - "pods"
        apiVersions:
          - "*"
        operations:
          - CREATE
        scope: "Namespaced"