apiVersion: v1
kind: Namespace
metadata:
  name: quay-away
---
apiVersion: v1
kind: Service
metadata:
  name: quay-away
  namespace: quay-away
  labels:
    run: quay-away
spec:
  ports:
    - name: webhook
      port: 443
      targetPort: 443
  selector:
    run: quay-away
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-away
  namespace: quay-away
  labels:
    run: quay-away
spec:
  replicas: 1
  selector:
    matchLabels:
      run: quay-away
  template:
    metadata:
      name: quay-away
      labels:
        run: quay-away
    spec:
      containers:
        - name: webhook
          image: jwalther/quay-away
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "443"
          volumeMounts:
            - name: webhook-ssl
              mountPath: /webhook-ssl
              readOnly: true
          ports:
            - containerPort: 443
              name: webhook
          livenessProbe:
            httpGet:
              path: /health
              port: webhook
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: webhook-ssl
          secret:
            secretName: quay-away
